# Nixpacks Configuration for Railway

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["cd client && npm ci"]

[phases.build]
cmds = ["cd client && npm run build -- --configuration production"]

[start]
cmd = "cd client && npx serve -s dist/client/browser -l $PORT"
